import {ethers} from 'ethers';

/**
 * @class TrustService
 * @description  Verifies Remote Attestation (RA) reports from Intel TDX / 0G Labs.
 * Ensures that the AI inference was actually executed inside a secure hardware enclave.
 * 
 */

export class TrustService {

    private enclaveSignerAddress: string;

    constructor(expectedEnclaveAddress: string) {
        this.enclaveSignerAddress = expectedEnclaveAddress;
    }

    /**
     * @dev Cryptographically verifies the hardware quote (proof).
     * @param proof The signature generated by the TEE hardware.
     * @param decisionPayload The AI decision (e.g., "BUY 10 ETH").
     * @returns boolean True if the hardware signature is authentic.
     * 
     */
    async verifyRemoteAttestation(proof: string, decisionPayload: string): Promise<boolean> {
        console.log("[TrustService] Verifying Intel TDX Remote Attestation Quote...");
        
        try {
            // In a real environment, we would verify the quote against Intel's API or a smart contract.
            // Here, we simulate verifying that the payload was signed by the registered enclave key.
            const payloadHash = ethers.keccak256(ethers.toUtf8Bytes(decisionPayload));
            const recoveredAddress = ethers.recoverAddress(payloadHash, proof);

            const isValid = recoveredAddress.toLowerCase() === this.enclaveSignerAddress.toLowerCase();
            
            if (isValid) {
                console.log("[TrustService] Verification SUCCESS: AI execution is securely sealed.");
            } else {
                console.warn("[TrustService] Verification FAILED: Signature mismatch. Potential tampering!");
            }

            return isValid;
        } catch (error) {
            console.error("[TrustService] Error during verification:", error);
            return false;
        }
    }
}